# Generated by Django 5.1.6 on 2025-02-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=30)),
                ('user_password', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
    ]
