# Generated by Django 4.1.4 on 2025-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=30)),
                ('user_password', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
    ]
