# Generated by Django 4.1.4 on 2025-01-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assignment_course_quiz_video_studentquiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quiz'),
        ),
    ]
