# Generated by Django 4.1.4 on 2025-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_coursefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback',
            field=models.TextField(max_length=200),
        ),
    ]
