# Generated by Django 4.1.4 on 2025-02-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_teacher_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cooperate',
            field=models.BinaryField(default=b'0'),
        ),
    ]
