# Generated by Django 5.1.5 on 2025-02-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_teacher_cooperate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('question_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('survey_question', models.TextField(max_length=300)),
                ('survey_name', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_answer', models.BinaryField(default=None)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.survey')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
