# Generated by Django 5.1.5 on 2025-02-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_survey_surveyanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
