# Generated by Django 4.1.4 on 2025-02-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_survey_surveyanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_ans_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_ans_yes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
