# Generated by Django 4.1.4 on 2025-02-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_survey_survey_ans_no_survey_survey_ans_yes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_ans_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_ans_yes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
