# Generated by Django 4.1.4 on 2025-02-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_survey_survey_ans_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_ans_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_ans_yes',
            field=models.IntegerField(default=0),
        ),
    ]
