# Generated by Django 4.1.4 on 2025-02-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_survey_survey_ans_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='assignment_file_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
    ]
