# Generated by Django 4.1.4 on 2025-02-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_studentassignment_assignment_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='quiz_id',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='StudentQuiz',
        ),
    ]
