# Generated by Django 4.1.4 on 2025-02-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_quizquestion_quiz_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_feedback',
        ),
    ]
