# Generated by Django 4.1.4 on 2025-02-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_student_teacher_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_feedback', models.TextField(blank=True, null=True)),
                ('teacher_name', models.TextField(max_length=30)),
                ('student_name', models.TextField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
