# Generated by Django 4.1.4 on 2025-02-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_teacherfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfeedback',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
